name: Build Aubio Wheel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - 

      - name: Install Dependencies
        run: |
          python -m poetry install

      - name: Clone Aubio Repo
        run: |
          git clone https://git.aubio.org/aubio/aubio.git
          cd aubio
          poetry install

      - name: Build Aubio Wheel
        run: |
          cd aubio
          poetry build

      - name: Upload Wheel as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aubio_wheel
          path: aubio/dist/*.whl
          retention-days: 1
