name: Discord Release

on: 
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      message:
       description: 'Message'
       default: 'Test'
       required: false
       
jobs:
  Send_Messages:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: YeonV/discord-webhook@v5.3.1
      with:
        webhook-url: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        content: "${{ github.event.inputs.message }}"
        thread-name: "YOO"
